# Generated by Django 4.0.4 on 2022-04-15 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Listing Date')),
                ('location', models.CharField(choices=[('S', 'San Diego'), ('B', 'Santa Barabara'), ('M', 'Malibu')], default='S', max_length=200)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.house')),
            ],
        ),
    ]
