# Generated by Django 4.0.4 on 2022-04-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_house_id_alter_listing_id_alter_realtor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='location',
        ),
        migrations.AlterField(
            model_name='house',
            name='city',
            field=models.CharField(choices=[('S', 'San Diego'), ('B', 'Santa Barabara'), ('M', 'Malibu')], default='S', max_length=200),
        ),
    ]
