# Generated by Django 4.0.4 on 2022-04-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_listing_location_alter_house_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='realtors',
        ),
        migrations.AddField(
            model_name='listing',
            name='realtors',
            field=models.ManyToManyField(to='main_app.realtor'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
