# Generated by Django 4.0.4 on 2022-04-17 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_house_realtors_listing_realtors_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='house',
            name='price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='realtors',
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='main_app.realtor'),
        ),
    ]
