# Generated by Django 4.0.2 on 2022-04-17 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20220416_2201'),
        ('main_app', '0009_alter_listing_realtor'),
    ]

    operations = [
    ]
