# Generated by Django 4.0.4 on 2022-04-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_merge_20220417_1923'),
        ('main_app', '0010_merge_20220417_1924'),
    ]

    operations = [
    ]
