# Generated by Django 4.0.4 on 2022-04-17 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_merge_20220417_2156'),
        ('main_app', '0012_alter_house_id_alter_listing_id_alter_realtor_id'),
    ]

    operations = [
    ]
