# Generated by Django 4.0.2 on 2022-04-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_house_id_alter_images_id_alter_listing_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='images',
            field=models.ImageField(default='https://i.imgur.com/FamLaMp.jpeg', upload_to=''),
        ),
    ]
