# Generated by Django 4.0.2 on 2022-04-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_rename_images_realtor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='image',
            field=models.FileField(default='https://i.imgur.com/FamLaMp.jpeg', upload_to=''),
        ),
    ]
