# Generated by Django 4.0.2 on 2022-04-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_realtor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='image',
            field=models.FileField(default='/Users/raullopez/code/estates/media/files/maxresdefault.jpg', upload_to=''),
        ),
    ]
