# Generated by Django 4.0.4 on 2022-04-19 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_image'),
        ('main_app', '0021_remove_realtor_image'),
    ]

    operations = [
    ]
