# Generated by Django 2.2.12 on 2022-04-19 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_remove_realtor_image'),
        ('main_app', '0017_image'),
    ]

    operations = [
    ]
