# Generated by Django 4.0.4 on 2022-04-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='realtors'),
        ),
    ]
