# Generated by Django 4.0.4 on 2022-04-19 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_realtor_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='images',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
