# Generated by Django 4.0.4 on 2022-04-19 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_merge_20220419_0523'),
        ('main_app', '0025_delete_images_delete_photo'),
    ]

    operations = [
    ]
