# Generated by Django 4.0.4 on 2022-04-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_images_remove_realtor_image_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='images',
        ),
        migrations.AddField(
            model_name='realtor',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='realtors'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
