# Generated by Django 4.0.2 on 2022-04-19 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_merge_20220419_2034'),
        ('main_app', '0028_delete_images_realtor_image_delete_photo'),
    ]

    operations = [
    ]
